version: 2
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dart
    groups:
      pub-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
    groups:
      github-actions:
        patterns:
          - "*"
