import 'dart:io';

import 'package:path/path.dart' as p;

/// Directory names never worth copying from a local template: VCS metadata and
/// build/tooling caches. They are regenerated by `pub get` / a build and would
/// only bloat (or corrupt) the scaffolded project.
const _skipDirs = {
  '.git',
  '.dart_tool',
  'build',
  '.fvm',
  '.gradle',
  'Pods',
  '.symlinks',
};

/// Copies the template tree at [fromDir] into [toDir], skipping VCS and build
/// caches ([_skipDirs]) and symlinks.
///
/// Backs `fst create --template-path`: scaffolding from a local checkout instead
/// of cloning the remote (useful offline, for a fork, or to smoke-test the CLI
/// against an unpublished template). The caller still runs the normal clean-slate
/// and rewrite steps over the copy, so dev-only submodules are stripped there.
Future<void> copyLocalTemplate(String fromDir, String toDir) async {
  final from = Directory(fromDir);
  if (!from.existsSync()) {
    throw ArgumentError('Template path does not exist: $fromDir');
  }
  await _copyDir(from, Directory(toDir));
}

Future<void> _copyDir(Directory from, Directory to) async {
  await to.create(recursive: true);
  await for (final entity in from.list(followLinks: false)) {
    final name = p.basename(entity.path);
    if (entity is Directory) {
      // Skip the whole subtree rather than descending into it.
      if (_skipDirs.contains(name)) continue;
      await _copyDir(entity, Directory(p.join(to.path, name)));
    } else if (entity is File) {
      await entity.copy(p.join(to.path, name));
    }
    // Links fall through: a template's symlinks (e.g. ios/.symlinks) are build
    // artifacts, regenerated by pub get / pod install.
  }
}
